"""File output writers and the intervention-coverage math.

Coverage rules (why a "recommendation" is not counted as done): a
recommendation is generated by the rule engine before any human acts, and a
freshly-generated motivational message is just a draft sitting in the UI.
Neither should move the needle on "is this student actually being taken care
of?" — only a recorded attempt or completed action should. This is why the
statuses below are split into attempt vs. success vs. completed buckets
instead of one generic "handled" flag.
"""
from __future__ import annotations

import json
from datetime import date
from pathlib import Path
from typing import Any

import pandas as pd

# A recommendation alone never counts toward coverage — see module docstring.
ATTEMPT_STATUSES = {"in_progress", "attempted", "no_answer", "message_sent", "booked",
                     "completed", "follow_up_required", "escalated", "resolved"}
# A no-answer call is an attempt, not a success — it is deliberately excluded here.
SUCCESS_STATUSES = {"completed", "resolved", "message_sent", "booked"}
COMPLETED_STATUSES = {"completed", "resolved"}
OPEN_STATUSES = {"recommended", "in_progress", "attempted", "no_answer", "follow_up_required", "escalated"}


def needs_intervention_mask(risk_df: pd.DataFrame) -> pd.Series:
    return (risk_df["risk_level"].isin(["Critical", "High", "Medium"])) | (risk_df["below_target"] == True)  # noqa: E712


def coverage_metrics(risk_df: pd.DataFrame, interventions_df: pd.DataFrame, as_of_date: date,
                      target_coverage: float) -> dict[str, Any]:
    needing = risk_df[needs_intervention_mask(risk_df)]
    needing_ids = set(needing["student_id"])
    n_needing = len(needing_ids)

    if interventions_df.empty or n_needing == 0:
        has_any = has_attempt = has_success = has_completed = overdue_ids = due_today_ids = set()
    else:
        iv = interventions_df[interventions_df["student_id"].isin(needing_ids)].copy()
        iv["due_date"] = pd.to_datetime(iv["due_date"])
        has_any = set(iv["student_id"])
        has_attempt = set(iv.loc[iv["status"].isin(ATTEMPT_STATUSES), "student_id"])
        has_success = set(iv.loc[iv["status"].isin(SUCCESS_STATUSES), "student_id"])
        has_completed = set(iv.loc[iv["status"].isin(COMPLETED_STATUSES), "student_id"])
        overdue = iv[iv["status"].isin(OPEN_STATUSES) & (iv["due_date"] < pd.Timestamp(as_of_date))]
        overdue_ids = set(overdue["student_id"])
        due_today = iv[(iv["due_date"].dt.date == as_of_date) & iv["status"].isin(OPEN_STATUSES)]
        due_today_ids = set(due_today["student_id"])

    def pct(subset: set) -> float:
        return round(100 * len(subset & needing_ids) / n_needing, 1) if n_needing else 0.0

    projected_ids = has_success | due_today_ids
    successful_count = len(has_success & needing_ids)
    target_count = round(target_coverage * n_needing)

    return {
        "students_needing_intervention": n_needing,
        "recommendation_coverage": pct(has_any),
        "contact_attempt_rate": pct(has_attempt),
        "successful_interaction_rate": pct(has_success),
        "completed_intervention_rate": pct(has_completed),
        "overdue_intervention_rate": pct(overdue_ids),
        "projected_coverage": pct(projected_ids),
        "successful_interaction_count": successful_count,
        "target_count": target_count,
        "additional_students_needed": max(0, target_count - successful_count),
    }


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, default=str, ensure_ascii=False))


def write_csv(df: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)


def write_jsonl(records: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as f:
        for r in records:
            f.write(json.dumps(r, default=str, ensure_ascii=False) + "\n")


def build_risk_roster_df(risk_df: pd.DataFrame) -> pd.DataFrame:
    cols = [
        "student_id", "student_name", "campus_id", "facilitator_email", "grade", "learning_track",
        "quiz1_score", "target_score", "gap_to_target", "below_target",
        "risk_score", "risk_level", "priority_score", "confidence", "urgency_score",
        "reason_codes", "pattern_codes", "recommended_action", "action_priority", "due_date", "next_step",
        "days_until_quiz2", "attendance_trend", "practice_trend",
        "quiz_percentile", "attendance_percentile", "practice_percentile",
    ]
    df = risk_df[cols].copy()
    df["reason_codes"] = df["reason_codes"].apply(lambda v: ";".join(v) if isinstance(v, list) else v)
    df["pattern_codes"] = df["pattern_codes"].apply(lambda v: ";".join(v) if isinstance(v, list) else v)
    return df


def build_facilitator_worklist_df(risk_df: pd.DataFrame) -> pd.DataFrame:
    cols = ["facilitator_email", "student_id", "student_name", "recommended_action", "action_priority",
            "due_date", "estimated_minutes", "risk_level", "next_step"]
    return risk_df[cols].rename(columns={"recommended_action": "action_type", "action_priority": "priority"}).copy()


def print_console_summary(stats: dict, output_paths: list[str]) -> None:
    print("\n" + "=" * 72)
    print("BOON ACADEMY INTERVENTION COMMAND CENTER — pipeline run summary")
    print("=" * 72)
    print(f"As of Day {stats['as_of_day']}  |  {stats['days_until_quiz2']} days until Quiz 2")
    print(f"Students:            {stats['total_students']}")
    print(f"Campuses:            {stats['total_campuses']}")
    print(f"Facilitators:        {stats['total_facilitators']}")
    print(f"Below target:        {stats['below_target_count']} ({stats['below_target_pct']:.1f}%)")
    print(f"Post-quiz activity:  {stats['post_quiz_activity_pct']:.1f}% of students who need it")
    print(f"Successful interaction rate: {stats['successful_interaction_rate']:.1f}%  (target 80%)")
    print(f"Additional students needed to hit target: {stats['additional_students_needed']}")
    print("-" * 72)
    rc = stats["risk_counts"]
    print(f"Risk levels -> Critical: {rc.get('Critical', 0)}  High: {rc.get('High', 0)}  "
          f"Medium: {rc.get('Medium', 0)}  Low: {rc.get('Low', 0)}")
    print(f"Recommended actions generated: {stats['recommended_action_count']}")
    print(f"LLM calls -> success: {stats['llm_success_count']}  fallback: {stats['llm_fallback_count']}")
    print(f"Data-quality issues flagged: {stats['data_quality_issue_count']}")
    print("-" * 72)
    print("Outputs written:")
    for p in output_paths:
        print(f"  - {p}")
    print("=" * 72 + "\n")
